# Generated by Django 3.1 on 2023-11-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20231118_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('storage_capacity', models.CharField(max_length=200, unique=True)),
                ('hard_disk_interface', models.TextField(max_length=200, unique=True)),
                ('brand', models.CharField(max_length=200, unique=True)),
                ('special_feature', models.CharField(max_length=200, unique=True)),
                ('product_description', models.TextField(blank=True, max_length=500)),
                ('compatible_devices', models.TextField(blank=True, max_length=200)),
                ('installation_type', models.TextField(blank=True, max_length=200)),
                ('color', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
